# 참고: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
name: Publish Package to GitHub Packages
on:
  release:
    types: [published]
    paths:
      - ".github/workflows/publish-npm.yml",
      - "packages/catshark-core",
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "packages/catshark-core"

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn

      # - run: yarn test

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
